ARG BTL_COMMIT=ad874b078eff9c91ae4d89b146f1bd48195b57b7

FROM rust:1.93-alpine AS builder
RUN apk add --no-cache musl-dev git
WORKDIR /btl
RUN git clone https://github.com/jscott3201/rusty-bacnet-btl-harness.git . \
    && git checkout ${BTL_COMMIT}
RUN cargo build --release -p bacnet-btl

FROM alpine:3.21
RUN apk add --no-cache ca-certificates
COPY --from=builder /btl/target/release/bacnet-test /usr/local/bin/
ENTRYPOINT ["bacnet-test"]
